### ISSUE TITLE
Using WinMerge with the extension

### ISSUE THREAD

**Issue by ulgnot** [RandomEngy/VSCodeGitDiffAndMergeTool#2]
[diff]
    tool = winmerge
[difftool "winmerge"]
	cmd = \"C:\\Program Files\\WinMerge\\WinMergeU.exe" \"$LOCAL\" \"$REMOTE\"
[merge]
    tool = winmerge
[mergetool]
    keepbackup = false
[mergetool "winmerge"]
    cmd = \"C:\\Program Files\\WinMerge\\WinMergeU.exe" \"$REMOTE\" \"$LOCAL\" \"$BASE\" \"$MERGED\"
    trustexitcode = true

The two lines with WinMerge would cause error.  Using the example of beyondcompare4 would not have the error although I have no Beyond Compare 4 installed.  
> git rev-parse --show-toplevel
fatal: bad config line 20 in file C:/Users/thisis.me/.gitconfig
> git rev-parse --show-toplevel
fatal: bad config line 20 in file C:/Users/thisis.me/.gitconfig

Can you please help?  Or is this an issue with WinMerge?  Thank you!

**Comment by RandomEngy** [comment]
It sounds like git is having trouble parsing your .gitconfig file. What is on line 20?

**Comment by ulgnot** [comment]
Thanks for quick response.  

I have 
![image](https://user-images.githubusercontent.com/30092324/82335303-22cac380-99b7-11ea-99cc-f9283bb1099a.png)
to point at 
![image](https://user-images.githubusercontent.com/30092324/82335547-7f2de300-99b7-11ea-9716-204d38bc7e96.png)

I just played with it more by toggling between Win Merge and BC4.  
With only the portion about the tool change, I have the following... 
![image](https://user-images.githubusercontent.com/30092324/82337573-ed73a500-99b9-11ea-9453-3fcdd50f3d15.png)

![image](https://user-images.githubusercontent.com/30092324/82337854-37f52180-99ba-11ea-9c1f-55b7b8b6e25b.png)

I am wondering it is something about WinMerge, and maybe it could not take the additional parameters like \"$LOCAL\" \"$REMOTE\", but not sure why this could cause the extension to complain about the .gitconfig file.

**Comment by RandomEngy** [comment]
I am guessing it's because you haven't escaped one of the " marks on line 20.

`cmd = \"C:\\Program Files\\WinMerge\\WinMergeU.exe" \"$LOCAL\" \"$REMOTE\"`

should be

`cmd = \"C:\\Program Files\\WinMerge\\WinMergeU.exe\" \"$LOCAL\" \"$REMOTE\"`

**Comment by ulgnot** [comment]
That is it.  Thanks!  
Sorry for wasting your time.  It is embarrassing...
