### ISSUE TITLE
Support for WSL

### ISSUE THREAD

**Issue by cj-obrien** [RandomEngy/VSCodeGitDiffAndMergeTool#6]
Thanks for writing this extension! Any idea whether it could be configured/adapted to support WSL? In this use-case VScode and the external diff/merge tool (Beyond Compare, in my case) are native Windows applications while the git repo resides within the WSL filesystem. 

With the (Windows) git config modified as shown in the README, I get the following notification from the extension when attempting to launch the merge tool (by right-clicking on a file with conflicts in the Source Control view and selecting Launch merge tool): 

fatal: not a git repository (or any of the parent directories): .git

**Comment by RandomEngy** [comment]
I have basically no experience with WSL and not a whole lot of spare time but would be willing to take a pull request that adds support. The current extension code is tiny (73 lines) so it should be easy to get started.

**Comment by cj-obrien** [comment]
I think this change is non-trivial, unfortunately. IIUC when working with a WSL workspace this extension runs on the remote extension host under WSL. That implies that the Simple Git package is invoking the git binary provided by the WSL distro; until WSL GUI support drops attempting to launch a graphical diff tool within WSL won't work out of the box.
