### ISSUE TITLE
Disable popup

### ISSUE THREAD

**Issue by lonix1** [RandomEngy/VSCodeGitDiffAndMergeTool#7]
Is it possible to disable that popup ("launching the merge tool...") that show in the bottom right corner? It gets annoying to expand and then close it each time.

Love this extension otherwise, thank you!

**Comment by RandomEngy** [comment]
Do you have any special settings on VSCode? I thought those messages went away on their own.

**Comment by RandomEngy** [comment]
That one usually closes on its own for me. Does it stay open until you manually dismiss it?

**Comment by lonix1** [comment]
No they hang around for a while, I always close them manually.

I assume for you they disappear on their own? In that case it must be "just me".

Thanks once again for this useful extension.

**Comment by lonix1** [comment]
You asked if I fiddled with any settings for this... are you aware of any that could cause this problem?

BTW my specs:
vscode latest version
extension latest version
linux/ubuntu 20

**Comment by RandomEngy** [comment]
Yeah looks like they are supposed to show only briefly and hide themselves after 10-15 seconds:

https://code.visualstudio.com/api/references/extension-guidelines#notifications

You could open an issue here to fix your general problem:

https://github.com/Microsoft/vscode/labels/workbench-notifications

I've published v1.0.5 which adds an option to disable the notification on launching the merge tool. It's under Settings -> Extensions -> Git Diff and Merge Tool.

**Comment by lonix1** [comment]
Thanks that's an excellent addition, solved my issues! (And I'll look into the popup issue as you recommended.)

---
By the way a suggestion: it may be a good idea to add a link from the repo to [the extension page](https://marketplace.visualstudio.com/items?itemName=david-rickard.git-diff-and-merge-tool) to make your extension more "discoverable" both ways.

**Comment by RandomEngy** [comment]
That's a good thought. Though the README.md in GitHub is getting automatically used as the listing for the extension on Visual Studio Marketplace. So the extension page would end up linking to itself.

**Comment by lonix1** [comment]
A workaround: you could consider what some other extensions have done, by placing the link in the "title" in the repo (it's shown on the top right on the main repo page).

Your title is "Visual Studio Code extension to launch the git difftool and mergetool". Other repos then have a link after that, [e.g.](https://github.com/mhutchie/vscode-git-graph), [e.g.](https://github.com/DonJayamanne/gitHistoryVSCode)

**Comment by RandomEngy** [comment]
Ahh good call. There's a specific field for the website URL. Updated.
