### ISSUE TITLE
.gitconfig for mac

### ISSUE THREAD

**Issue by renaco** [RandomEngy/VSCodeGitDiffAndMergeTool#8]
Hello there!

I want to know what is the steps to configure or path  for config on iOS version.

Regards!

**Comment by RandomEngy** [comment]
I've never done it, but many diff/merge tools have guides on how to set it up with Git. For instance, Beyond Compare has a Mac version: https://www.scootersoftware.com/support.php?zz=kb_vcs_osx

**Comment by renaco** [comment]
Thanks for answer me!
